### ISSUE TITLE
0.8.7 Regression: Invalid note count

### ISSUE THREAD

**Issue by esibun** [wcko87/lr2oraja#5]
Hello,

It seems specifically with the 0.8.7 release of LR2oraja that judgments are calculated incorrectly such that at the end of a song, PGREAT + GREAT + GOOD + BAD + POOR does not equal the total note count.

I'm not aware of any mechanical differences that would explain the discrepency.

Specifically, I tested with "Brave My Soul -Flareness Heart-" in the Satellite 1 folder with a replay file.  With Beatoraja 0.8.7 and LR2oraja 0.8.6 I get the same result.  With LR2oraja 0.8.7, I get a judgment sum 3 higher than the note count for the song; all extra judgments seem to be POORs:

LR2oraja 0.8.6:
![Screenshot 2024-03-09 20-52-45](https://github.com/wcko87/lr2oraja/assets/2644839/ba73efd4-e997-47c0-bc3b-6e084effe652)

LR2oraja 0.8.7 (note count is -3, minus symbol doesn't render due to missing glyph in skin):
![mpv-shot0003](https://github.com/wcko87/lr2oraja/assets/2644839/4e0d8629-a179-49eb-9184-5b9e5f648292)

**Comment by wcko87** [comment]
Thank you so much for catching this issue. I've identified and fixed the cause of the issue and [re-released LR2oraja 0.8.7](https://github.com/wcko87/lr2oraja/releases).

I had missed that issue in my testing somehow. The extra poors apparently did show up in my tests previously, but I wasn't looking out for them so I didn't notice them. I've re-checked the numbers with my tests and it seems to be correct now. Could you run your replay as well to check that this issue is indeed resolved?

The bug comes from a refactor in JudgeManager between 0.8.6 and 0.8.7 changing how updateMicro() is affected by bool[] judgeVanish. I had updated LR2oraja's multi-bad code to account for the refactor, but had made a small logical error in doing so.

This caused multi-bad (see final bullet point of [0.8.5's release description](https://github.com/wcko87/lr2oraja/releases/tag/build4501107977)) judgements to be detected as simultaneously a BAD and a POOR, hence the additional POORS.

**Comment by esibun** [comment]
Everything looks good on my end with the updated jar, thanks for the quick turnaround!
